# Part 1

In [1]:
import csv
import os
import nltk
from PIL import Image
import numpy as np
import torch
import torchvision.transforms as transforms
import torchvision.models as models
from transformers import BertTokenizer
import string
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder



In [2]:
# Create a LabelEncoder object
label_encoder = LabelEncoder()

In [3]:
# Initialize the NLTK tokenizer and set it to use the Treebank tokenizer
#nltk.download('punkt')

# Define the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Define a translation table for removing punctuation
translator = str.maketrans('', '', string.punctuation)

# Define the transformation to be applied to the images
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# Load the VGG16 model
vgg16 = models.vgg16(pretrained=True)

# Set the model to evaluation mode
vgg16.eval()



C:\Users\Pakistan\anaconda3\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\Pakistan\anaconda3\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [4]:
import csv
import os

# Define the path to the CSV file containing the captions
csv_file = 'sentiment/sentiment1.csv'

# Define the path to the folder containing the images
data_dir = 'sentiment/sentiment_images'


# Read the CSV file
with open(csv_file, 'r') as f:
    reader = csv.reader(f)
    next(reader)  # Skip the header row
    captions1 = []
    imagefiles=[]
    for row in reader:
        filename = row[0]
        caption = row[1]
        img_path = os.path.join(data_dir, filename)
        if os.path.exists(img_path):
            img = Image.open(img_path).convert('RGB')
            img_tensor = transform(img)
            img_tensor = img_tensor.unsqueeze(0)
        
        # Extract the features from the image using VGG16
            with torch.no_grad():
                features = vgg16.features(img_tensor)
                features = features.view(features.size(0), -1)
            
            imagefiles.append(features)
            captions1.append((img_path, caption))
            
            

In [99]:
import csv
import os

# Define the path to the CSV file containing the captions
csv_file = 'sentiment/sentiment1.csv'

# Define the path to the folder containing the images
data_dir = 'sentiment/sentiment_images'


# Read the CSV file
with open(csv_file, 'r') as f:
    reader = csv.reader(f)
    next(reader)  # Skip the header row
    #captions1 = []
    #imagefiles=[]
    labels=[]
    for row in reader:
        filename = row[0]
        caption = row[1]
        label=row[2]
        img_path = os.path.join(data_dir, filename)
        if os.path.exists(img_path):
            labels.append(label)
            
            

In [6]:
#sacing images featuresas it tekes grate time to run 

imagefiles1=imagefiles.copy()

import pickle

# Save the image features to a file
with open('image_features.pickle', 'wb') as f:
    pickle.dump(imagefiles, f)

import pickle

# Load the image features from the file
with open('image_features.pickle', 'rb') as f:
    imagefiles = pickle.load(f)
    

In [98]:
#preprocessing captions. make it in tokens and in lower case



#precaptions=[]
raw_captions=[]

for i in range(len(captions1)):
    #captions.append(captions1[i][0])
    caption_raw=captions1[i][1]
    raw_captions.append(caption_raw)
    caption_tokens = tokenizer.tokenize(caption_raw.lower().translate(translator))    
    captions.append(caption_tokens)
    
    
    
 
    

In [8]:
len(captions)

39109

In [9]:
len(imagefiles)

39109

In [10]:
imagefiles




[tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([[0.0000, 0.4454, 0.0000,  ..., 0.0000, 0.0000, 0.0000

In [67]:
captions


[['a', 'plate', 'of', 'delicious', 'food', 'including', 'french', 'fries'],
 ['french',
  'fries',
  'are',
  'not',
  'a',
  'healthy',
  'food',
  'but',
  'it',
  'is',
  'an',
  'excellent',
  'food',
  'for',
  'teenagers'],
 ['the',
  'plate',
  'has',
  'one',
  'of',
  'my',
  'favorite',
  'foods',
  'on',
  'it',
  'french',
  'fries'],
 ['it', 'was', 'disgusting', 'food', 'not', 'just', 'bad', 'food'],
 ['a', 'plate', 'of', 'disgusting', 'food', 'found', 'at', 'a', 'diner'],
 ['the', 'meat', 'on', 'the', 'burger', 'looks', 'like', 'disgusting', 'food'],
 ['a', 'plate', 'of', 'delicious', 'food', 'including', 'french', 'fries'],
 ['french',
  'fries',
  'are',
  'not',
  'a',
  'healthy',
  'food',
  'but',
  'it',
  'is',
  'an',
  'excellent',
  'food',
  'for',
  'teenagers'],
 ['the',
  'plate',
  'has',
  'one',
  'of',
  'my',
  'favorite',
  'foods',
  'on',
  'it',
  'french',
  'fries'],
 ['it', 'was', 'disgusting', 'food', 'not', 'just', 'bad', 'food'],
 ['a', 'plat

In [12]:
labels



['1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1'

In [13]:
#here finding features of text by built in embeddings load it then converting each word in  data to vector


# load the embeddings


import numpy as np

embeddings_dict = {}
with open("glove.6B.50d.txt", 'r', encoding='utf8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], dtype='float32')
        embeddings_dict[word] = vector


In [14]:
# convert each word in your data into its corresponding embedding vector

embedded_data = []
for sentence in captions:
    embedded_sentence = []
    for word in sentence:
        if word in embeddings_dict:
            embedded_sentence.append(embeddings_dict[word])
    embedded_data.append(embedded_sentence)


In [15]:
#we have to pad sentence as to make all sentences with equal captions text

# pad each sentence to have the same length and convert the data to a numpy array

from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = max([len(sentence) for sentence in embedded_data])
padded_data = pad_sequences(embedded_data, maxlen=max_len, dtype='float32', padding='post')


In [16]:
padded_data

array([[[ 0.21705  ,  0.46515  , -0.46757  , ..., -0.043782 ,
          0.41013  ,  0.1796   ],
        [-0.63773  ,  0.83063  , -0.26741  , ..., -0.30956  ,
          0.10163  , -0.66864  ],
        [ 0.70853  ,  0.57088  , -0.4716   , ..., -0.22562  ,
         -0.093918 , -0.80375  ],
        ...,
        [ 0.       ,  0.       ,  0.       , ...,  0.       ,
          0.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       , ...,  0.       ,
          0.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       , ...,  0.       ,
          0.       ,  0.       ]],

       [[ 0.45339  ,  0.26154  , -1.3094   , ...,  0.19036  ,
          0.50769  , -0.61832  ],
        [ 0.28549  , -0.50842  , -0.97154  , ..., -0.67152  ,
         -0.062107 ,  0.62837  ],
        [ 0.96193  ,  0.012516 ,  0.21733  , ...,  0.14032  ,
         -0.38468  , -0.38712  ],
        ...,
        [ 0.       ,  0.       ,  0.       , ...,  0.       ,
          0.       ,  0.       ],
        [ 0.

# Train Test Split

In [136]:
#80% training 
#20% testing

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
text_train1, text_test1, image_train1, image_test1, label_train1, label_test1 = train_test_split(padded_data, imagefiles,labels, test_size=0.2, random_state=42)


 
text_train11, text_test11, image_train11, image_test11, label_train11, label_test11 = train_test_split(padded_data, imagefiles1,labels, test_size=0.2, random_state=42)


In [ ]:
#relu: return 0 if negative and 1 if positive creating non linearity by making negative values 0 and positive without change 
#Cross-entropy loss is a commonly used loss function in machine learning for classification problems. It measures the
#difference between the predicted probability distribution and the true probability distribution of the target labels
#Stochastic gradient descent (SGD) is an optimization algorithm used for minimizing the loss function of a machine learning model


In [19]:
# text_train11=text_train1.copy()
# text_test11=text_test1.copy()
# image_train11=image_train1.copy()
# image_test11=image_test1.copy()
# label_train11=label_train1.copy()
# label_test11=label_test1.copy()
imagefiles[0].shape[1]
#padded_data[0].size()

25088

# MultiModal

In [137]:
import torch
import torch.nn as nn
#it also use cross-entropy loss and stochastic gradient descent for calculating cross entropy loss and optimize model then with
#stochastic optimizer


In [30]:
class firstpart(nn.Module):
    #defning constructor of class
    def __init__(self, image_features_dim, text_features_dim, hidden_dim,num_classes):
        super(firstpart, self).__init__()
        
        self.image_features_dim = image_features_dim
        self.text_features_dim = text_features_dim
        self.hidden_dim = hidden_dim
        
        # Define layers , just defining layers in constructor
        #text layer
        self.text_hidden_layer = nn.Linear(text_features_dim, hidden_dim)
        #images layer
        self.image_hidden_layer = nn.Linear(image_features_dim, hidden_dim)
        #hidden layer1 , dno kei combine ho gi to sab sei pehlei is layer kei pas aye gi that's why dim*2
        self.hidden_layer1 = nn.Linear(hidden_dim*2, hidden_dim)
        #hiddenlayer2 , then willl cme here
        self.hidden_layer2 = nn.Linear(hidden_dim, hidden_dim)
        #hidden layer3
        self.hidden_layer3 = nn.Linear(hidden_dim, hidden_dim)
        #last hidden layer
        self.hidden_layer4 = nn.Linear(hidden_dim, hidden_dim)
        #output layer
        self.output_layer = nn.Linear(hidden_dim, num_classes) # num_classes is the number of output classes
        
    def forward(self, text_features, image_features,text_features_dim,image_features_dim):
        print("neha2")
        # Image features pass through hidden layer
        #image_features = image_features.view(-1, image_features_dim)
        image_hidden = self.image_hidden_layer(image_features)
        image_hidden = nn.functional.relu(image_hidden)
        print("image hidden",image_hidden)
        
        print("neha1")
        #print(self.text_hidden_layer.shape[0])
        print(text_features.shape[0])
        # Text features pass through hidden layer
        #text_features = text_features.view(-1, text_features_dim)
        print("text features before transpose",text_features)
        text_features=text_features.transpose(0,1)
        print("text features after transpose",text_features)
        text_hidden = self.text_hidden_layer(text_features)
        text_hidden = nn.functional.relu(text_hidden)
        print("text hidden",text_hidden)
        
        print("neha3")
        print(text_hidden.size())
        print(image_hidden.size())
            
        #text_hidden = text_hidden.transpose(0, 1)
        image_hidden = image_hidden.transpose(0, 1)
        
        
        # Concatenate text and image hidden layers
        concat_hidden = torch.cat([text_hidden, image_hidden],dim=1)
        print("concat hidden",concat_hidden)
        
#         print("neha4")
#         # Pass through additional hidden layers
#         # Pass through additional hidden layers
        #ye do baar is liye kr rhi takei first hidden layer sei multiply ho jae shape 
        concat_hidden = concat_hidden.transpose(0, 1)
        concat_hidden=torch.cat([concat_hidden, concat_hidden], dim=1)
        
        print("neha4")
#        concat_hidden=concat_hidden.transpose(0,1)
        #self.hidden_layer1.weight.data = self.hidden_layer1.weight.data.transpose(0, 1)

        #concat to first hidden layer
        hidden1 = self.hidden_layer1(concat_hidden)   
        hidden1 = nn.functional.relu(hidden1)
        print("Hidden 1",hidden1)
 
        #first hidden layer to secod
        print("neha5")
        hidden2 = self.hidden_layer2(hidden1)
        hidden2 = nn.functional.relu(hidden2)
        print("Hidden 2",hidden2)
        
        #second hidden layer to third
        print("neha6")
        hidden3 = self.hidden_layer3(hidden2)
        hidden3 = nn.functional.relu(hidden3)
        print("Hidden 3",hidden3)
        
        ##3rd to 4th
        print("neha7")
        hidden4 = self.hidden_layer4(hidden3)
        hidden4 = nn.functional.relu(hidden4)
        print("Hidden 4",hidden4)
        
        #output layer
        print("neha8")
        # Pass through output layer
        output = self.output_layer(hidden4)
        
        return output



# image_features_dim: number of neurons in image layer
# text_features_dim:  number of neurons in text layer
# hidden_dim: hidden layer mei kitne neurons hon gei?
# num_classes :output kitne classes pe map ho ga 

image_feature_dim = imagefiles[0].shape[1] # Assumes all image features have same dimensions
print("image_feature_dim",image_feature_dim)
text_feature_dim = padded_data.shape[1]
print("text_feature_dim",text_feature_dim)

model = firstpart(image_features_dim=image_feature_dim, text_features_dim=text_feature_dim, hidden_dim=50, num_classes=10)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Train the model
num_epochs = 10
batch_size = 32
num_batches = len(text_train1) // batch_size

all_pred_labels = []
all_true_labels = []

for epoch in range(num_epochs):
    for i in range(num_batches):
        #ye sab hum batchsize kei mutabiq utna utna chunk utha rhei 
        text_batch = text_train1[i*batch_size:(i+1)*batch_size]
        image_batch1 = image_train1[i*batch_size:(i+1)*batch_size]
        label_batch = label_train1[i*batch_size:(i+1)*batch_size]

        #tamam image tsnrors to aik tensor kr rhei 
        image_batch1 = [torch.tensor(feature) for feature in image_batch1] 
        image_batch = torch.stack(image_batch1)
        #25088 as size of each image in dataset, here making single dimension with this size
        image_batch = image_batch.view(-1, 25088)

        #selects the first element from text_batch as the input text for the current batch.
        text_batch = text_batch[0, :, :]
        #normaliseing input text by diviidng each to l2norm
        text_batch /= np.linalg.norm(text_batch, axis=-1, keepdims=True)
        
        #numpy array is converted to a tensor.
        text_features_tensor = torch.Tensor(text_batch)
        #number of features in the input text tensor
        text_features_dim = text_batch.shape[-1]  # num_features
        
        #use label encoding kiyu kei wo strings ki type hai 
        # Forward pass
        output = model(text_features_tensor, image_batch, text_features_dim, image_features_dim=image_batch.shape[1])
        #print(output)
    
        # Fit the encoder to the label batch
        label_encoder.fit(label_batch)

        # Convert the label batch to numerical values
        label_batch = label_encoder.transform(label_batch)
        tensor_1d = torch.tensor(label_batch, dtype=torch.long)

#         # Reshape the tensor to have 2 dimensions
#         tensor_2d = tensor_1d.reshape(-1, 1)
#         print("tensor_2d",tensor_2d.size())
        print(output.size())
        print(tensor_1d.size())
        # find rows with NaN values
        mask = torch.isnan(output).any(dim=1)

        # remove rows with NaN values
        output1 = output[~mask]
        if(output1.size()[0]==0):
            break
        loss = criterion(output1, tensor_1d)
        print("Loss ",loss)
        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    #hum kitni baar data show krwa rhei training data model ko     
    # Print the loss after each epoch
    print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
    
    
    
    


image_feature_dim 25088
text_feature_dim 96
neha2
image hidden tensor([[1.1891, 1.2233, 0.1326,  ..., 0.4473, 0.5582, 0.5819],
        [0.7639, 0.0000, 0.0000,  ..., 0.7647, 0.0343, 0.8982],
        [0.0000, 0.0705, 0.0000,  ..., 0.0000, 0.1306, 0.9237],
        ...,
        [0.5323, 0.0000, 0.0000,  ..., 0.0757, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5341,  ..., 0.6683, 0.0000, 0.3184],
        [0.2586, 1.2522, 0.0000,  ..., 1.1196, 2.4220, 0.3737]],
       grad_fn=<ReluBackward0>)
neha1
96
text features before transpose tensor([[ 0.0410,  0.0878, -0.0882,  ..., -0.0083,  0.0774,  0.0339],
        [-0.0326,  0.1163, -0.1044,  ..., -0.2357,  0.0875, -0.0188],
        [ 0.1220,  0.1268, -0.0919,  ..., -0.0544,  0.0610,  0.0957],
        ...,
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan]])
text features after transpose ten

C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/2118022279.py:114: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_batch1]
C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/2118022279.py:114: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_batch1]
C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/2118022279.py:114: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_

neha4
Hidden 1 tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<ReluBackward0>)
neha5
Hidden 2 tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<ReluBackward0>)
neha6
Hidden 3 tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<ReluBackward0>)
neha7
Hidd

Hidden 4 tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<ReluBackward0>)
neha8
torch.Size([82, 10])
torch.Size([32])
Epoch [10/10], Loss: 2.2758


C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/2118022279.py:114: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_batch1]
C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/2118022279.py:114: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_batch1]
C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/2118022279.py:114: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_

In [38]:
#here for predicting purpose 

class firstpart(nn.Module):
    def __init__(self, image_features_dim, text_features_dim, hidden_dim,num_classes):
        super(firstpart, self).__init__()
        
        self.image_features_dim = image_features_dim
        self.text_features_dim = text_features_dim
        self.hidden_dim = hidden_dim
        
        # Define layers
        self.text_hidden_layer = nn.Linear(text_features_dim, hidden_dim)
        self.image_hidden_layer = nn.Linear(image_features_dim, hidden_dim)
        self.hidden_layer1 = nn.Linear(hidden_dim*2, hidden_dim)
        self.hidden_layer2 = nn.Linear(hidden_dim, hidden_dim)
        self.hidden_layer3 = nn.Linear(hidden_dim, hidden_dim)
        self.hidden_layer4 = nn.Linear(hidden_dim, hidden_dim)
        self.output_layer = nn.Linear(hidden_dim, num_classes) # num_classes is the number of output classes
        
    def forward(self, text_features, image_features,text_features_dim,image_features_dim):
         
        # Image features pass through hidden layer
        #image_features = image_features.view(-1, image_features_dim)
        image_hidden = self.image_hidden_layer(image_features)
        image_hidden = nn.functional.relu(image_hidden)
         
        
         
        #print(self.text_hidden_layer.shape[0])
         
        # Text features pass through hidden layer
        #text_features = text_features.view(-1, text_features_dim)
         
        text_features=text_features.transpose(0,1)
         
        text_hidden = self.text_hidden_layer(text_features)
        text_hidden = nn.functional.relu(text_hidden)
         
            
        #text_hidden = text_hidden.transpose(0, 1)
        image_hidden = image_hidden.transpose(0, 1)
        
        
        # Concatenate text and image hidden layers
        concat_hidden = torch.cat([text_hidden, image_hidden],dim=1)
        
        
#         print("neha4")
#         # Pass through additional hidden layers
#         # Pass through additional hidden layers
        concat_hidden = concat_hidden.transpose(0, 1)
        concat_hidden=torch.cat([concat_hidden, concat_hidden], dim=1)
        
        
#        concat_hidden=concat_hidden.transpose(0,1)
        #self.hidden_layer1.weight.data = self.hidden_layer1.weight.data.transpose(0, 1)

        hidden1 = self.hidden_layer1(concat_hidden)   
        hidden1 = nn.functional.relu(hidden1)
         
        hidden2 = self.hidden_layer2(hidden1)
        hidden2 = nn.functional.relu(hidden2)
         
        
         
        hidden3 = self.hidden_layer3(hidden2)
        hidden3 = nn.functional.relu(hidden3)
         
        
         
        hidden4 = self.hidden_layer4(hidden3)
        hidden4 = nn.functional.relu(hidden4)
         
        
        
        # Pass through output layer
        output = self.output_layer(hidden4)
        
        return output





image_feature_dim = imagefiles[0].shape[1] # Assumes all image features have same dimensions
# print("image_feature_dim",image_feature_dim)
text_feature_dim = padded_data.shape[1]
# print("text_feature_dim",text_feature_dim)

model = firstpart(image_features_dim=image_feature_dim, text_features_dim=text_feature_dim, hidden_dim=50, num_classes=10)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Train the model
num_epochs = 10
batch_size = 32
num_batches = len(text_train1) // batch_size

all_pred_labels = []
all_true_labels = []

for epoch in range(num_epochs):
    for i in range(num_batches):
        text_batch = text_train1[i*batch_size:(i+1)*batch_size]
        image_batch1 = image_train1[i*batch_size:(i+1)*batch_size]
        label_batch = label_train1[i*batch_size:(i+1)*batch_size]

        image_batch1 = [torch.tensor(feature) for feature in image_batch1] 
        image_batch = torch.stack(image_batch1)
        image_batch = image_batch.view(-1, 25088)

        text_batch = text_batch[0, :, :]
        text_batch /= np.linalg.norm(text_batch, axis=-1, keepdims=True)
        
        text_features_tensor = torch.Tensor(text_batch)
        text_features_dim = text_batch.shape[-1]  # num_features
        
        # Forward pass
        output = model(text_features_tensor, image_batch, text_features_dim, image_features_dim=image_batch.shape[1])
        #print(output)
        
        # Fit the encoder to the label batch
        label_encoder.fit(label_batch)

        # Convert the label batch to numerical values
        label_batch = label_encoder.transform(label_batch)

        
        tensor_1d = torch.tensor(label_batch, dtype=torch.long)

#         # Reshape the tensor to have 2 dimensions
#         tensor_2d = tensor_1d.reshape(-1, 1)
#         print("tensor_2d",tensor_2d.size())
#         print(output.size())
#         print(tensor_1d.size())
        # find rows with NaN values
        mask = torch.isnan(output).any(dim=1)

        # remove rows with NaN values
        output1 = output[~mask]
        if(output1.size()[0]==0):
            break
        loss = criterion(output1, tensor_1d)
        #print("Loss ",loss)
        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Print the loss after each epoch
    #print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
    
    
    
    


C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/4236149345.py:108: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_batch1]
C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/4236149345.py:108: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_batch1]
C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/4236149345.py:108: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_

In [56]:
from sklearn.metrics import accuracy_score, f1_score, recall_score

# Define the validation dataset
#text_train11, text_test11, image_train11, image_test11, label_train11, label_test11 
image_feature_dim = imagefiles[0].shape[1] # Assumes all image features have same dimensions
print("image_feature_dim",image_feature_dim)
text_feature_dim = padded_data.shape[1]
print("text_feature_dim",text_feature_dim)

 
image_batch1 = [torch.tensor(feature) for feature in image_test11] 
image_batch = torch.stack(image_batch1)
image_batch = image_batch.view(-1, 25088)

text_batch = text_test11[0, :, :]
text_batch /= np.linalg.norm(text_batch, axis=-1, keepdims=True)
        
text_features_tensor = torch.Tensor(text_batch)
text_features_dim = text_batch.shape[-1]  # num_features
        
# label_encoder.fit(label_train11)

#         # Convert the label batch to numerical values
# label_batch = label_encoder.transform(label_batch)

        
# y_val = torch.tensor(label_batch, dtype=torch.long)


# Set the model to evaluation mode
model.eval()

# Disable gradient computation to save memory
with torch.no_grad():
    # Forward pass
    output = model(text_features_tensor, image_batch, text_features_dim, image_features_dim=image_batch.shape[1])

    # Convert the output to predicted labels
    pred_labels = torch.argmax(output, dim=1).numpy()

# Compute accuracy, F1 score, and recall
l=[]
for i in range(len(label_test11)):
    l.append(pred_labels[i])
    
pred_labels=l
    
accuracy = accuracy_score(label_test11, pred_labels)
print("accuracy",accuracy)

f1 = f1_score(label_test11, pred_labels, average='weighted')
print("flscore",f1)

recall = recall_score(label_test11, pred_labels, average='weighted')
print("recall",recall)

 

image_feature_dim 25088
text_feature_dim 96


C:\Users\Pakistan\AppData\Local\Temp/ipykernel_3004/1996276709.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_batch1 = [torch.tensor(feature) for feature in image_test11]


accuracy 0.6
flscore 0.7
recall 0.6


In [48]:
len(pred_labels)

7822

In [49]:
len(label_test11)

7822

In [53]:
print(image_features_tensor.size())
print(text_features_tensor.size())

torch.Size([39109, 25088])
torch.Size([96, 50])


# Part 2

In [125]:
# read the csv file
import pandas as pd 
df = pd.read_csv('sentiment/sentiment.csv')

# extract the 'word_sentiment' column and convert it to a list
word_sentiment_list = df['word_sentiment'].tolist()



#The code preprocesses the textual data by creating a dictionary mapping words to indices, converting the captions into one-hot
# encoded tensor representations, and normalizing them. The sentiment labels are also converted into a tensor. The model is then 
# trained using binary cross-entropy loss and stochastic gradient descent.


In [126]:
import torch
import torch.nn as nn
import numpy as np

class secondpart(nn.Module):
    def __init__(self, text_features_dim, hidden_dim, num_classes):
        #calls the initialization function of the parent class, nn.Module
        super(secondpart, self).__init__()
        #sets the dimensionality of the text features
        self.text_features_dim = text_features_dim
        #sets the number of hidden units
        self.hidden_dim = hidden_dim
        
        # Define layers
        self.text_hidden_layer = nn.Linear(text_features_dim, hidden_dim)
        #defines the first hidden layer that takes in the text hidden activations and produces new hidden activations
        self.hidden_layer1 = nn.Linear(hidden_dim, hidden_dim)
        #defines the second hidden layer
        self.hidden_layer2 = nn.Linear(hidden_dim, hidden_dim)
        #efines the third hidden layer.
        self.hidden_layer3 = nn.Linear(hidden_dim, hidden_dim)
        #defines the fourth hidden layer
        self.hidden_layer4 = nn.Linear(hidden_dim, hidden_dim)
        #defines the output layer which takes in the final hidden activations and produces a probability distribution over a set of classes
        self.output_layer = nn.Linear(hidden_dim, num_classes) # num_classes is the number of output classes
        
    def forward(self, text_features):
        #applies the text hidden layer to the input.
        text_hidden = self.text_hidden_layer(text_features)
        #applies the ReLU activation function to the text hidden activations.
        text_hidden = nn.functional.relu(text_hidden)
            
        # Pass through additional hidden layers
        #applies the first hidden layer to the text hidden activations
        hidden1 = self.hidden_layer1(text_hidden)
        #applies the ReLU activation function to the first hidden activations
        hidden1 = nn.functional.relu(hidden1)
        
        #here in other hidden layers , har layer sei piche wali us pe apply hho rhei hai or reu activation function lg rha 
        hidden2 = self.hidden_layer2(hidden1)
        hidden2 = nn.functional.relu(hidden2)
        
        hidden3 = self.hidden_layer3(hidden2)
        hidden3 = nn.functional.relu(hidden3)
        
        hidden4 = self.hidden_layer4(hidden3)
        hidden4 = nn.functional.relu(hidden4)
        
        # Pass through output layer
        #ye output layer pe pochnch gae hain
        output = self.output_layer(hidden4)
        
        return output
    

# Preprocess input data

#initializes an empty dictionary word_to_idx to map words to indices
word_to_idx = {}
#each caption or phir ech word pe loop
for caption in captions:
    for word in caption:
        #agr word dictionary mei nhi hai tou add krna 
        if word not in word_to_idx:
            #maps the word to a new index in dictionary
            word_to_idx[word] = len(word_to_idx)
            
#number of unique words from which we make dictionary
vocab_size = len(word_to_idx)
#creating tension mei dimensions and make it all zero
captions_tensor = torch.zeros(len(captions), len(word_to_idx))

#This loop iterates over each caption in captions and for each word in the caption, sets the corresponding element in 
#captions_tensor to 1.0. This converts each caption into a one-hot encoded tensor representation.
for i, caption in enumerate(captions):
    for word in caption:
        captions_tensor[i, word_to_idx[word]] = 1.0
        
#labels tensor from list conating word sentiment whoch we read from dataframe           
labels_tensor = torch.tensor(word_sentiment_list)



# Normalize captions tensor
#This converts the captions_tensor tensor to a numpy array and then normalizes each row of the array to have unit length using 
#numpy's linalg.norm() function. This creates a matrix of normalized caption embeddings.
captions_array = captions_tensor.numpy()
captions_array /= np.linalg.norm(captions_array, axis=-1, keepdims=True)
captions_array = captions_tensor.numpy()
captions_array /= np.linalg.norm(captions_array, axis=-1, keepdims=True)

# Convert labels to tensor
labels = torch.Tensor(word_sentiment_list)

# Define loss function and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

text_features_dim = captions_array.shape[-1] 

# Train model
num_epochs = 10
for epoch in range(num_epochs):
    running_loss = 0.0
    for i in range(len(captions)):
        # Clear gradients
        optimizer.zero_grad()

        # Forward pass
        output = model(captions_tensor[i], image_features_tensor[i], text_features_dim, image_features_dim=image_features_tensor.shape[1])
        loss = criterion(output, labels[i])

        # Backward pass
        #which calculates the gradients of the loss with respect to the model parameters. These gradients are then used to 
        #update the model parameters using optimizer.step()
        loss.backward()
        #method that is used to update the parameters of the model based on the gradients computed during backpropagation.
        #It updates the parameters with the gradients accumulated in the optimizer (which are computed during loss.backward()
        #After the gradients have been computed, optimizer.step() adjusts the weights of the model in the direction that 
        #minimizes the loss function, thereby improving the model's performance
        optimizer.step()
 
        #The loss for the current batch is added
        running_loss += loss.item()

    # Print average loss for the epoch
    print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, running_loss/len(captions)))
 

ValueError: too many dimensions 'str'

# Part 3

In [63]:
captions2=[]
for i in range(len(captions1)):
    #captions.append(captions1[i][0])
    caption_raw=captions1[i][1]
    captions2.append(caption_raw)
    
    

In [100]:
captions2


['a plate of delicious food including French fries.',
 'French fries are not a healthy food but it is an excellent food for teenagers.',
 'The plate has one of my favorite foods on it, French fries.',
 'It was disgusting food, not just bad food.',
 'A plate of disgusting food found at a diner.',
 'The meat on the burger looks like disgusting food.',
 'a plate of delicious food including French fries.',
 'French fries are not a healthy food but it is an excellent food for teenagers.',
 'The plate has one of my favorite foods on it, French fries.',
 'It was disgusting food, not just bad food.',
 'A plate of disgusting food found at a diner.',
 'The meat on the burger looks like disgusting food.',
 'a plate of delicious food including French fries.',
 'French fries are not a healthy food but it is an excellent food for teenagers.',
 'The plate has one of my favorite foods on it, French fries.',
 'It was disgusting food, not just bad food.',
 'A plate of disgusting food found at a diner.',

In [57]:
labels

['1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1'

In [58]:
captions 

[['a', 'plate', 'of', 'delicious', 'food', 'including', 'french', 'fries'],
 ['french',
  'fries',
  'are',
  'not',
  'a',
  'healthy',
  'food',
  'but',
  'it',
  'is',
  'an',
  'excellent',
  'food',
  'for',
  'teenagers'],
 ['the',
  'plate',
  'has',
  'one',
  'of',
  'my',
  'favorite',
  'foods',
  'on',
  'it',
  'french',
  'fries'],
 ['it', 'was', 'disgusting', 'food', 'not', 'just', 'bad', 'food'],
 ['a', 'plate', 'of', 'disgusting', 'food', 'found', 'at', 'a', 'diner'],
 ['the', 'meat', 'on', 'the', 'burger', 'looks', 'like', 'disgusting', 'food'],
 ['a', 'plate', 'of', 'delicious', 'food', 'including', 'french', 'fries'],
 ['french',
  'fries',
  'are',
  'not',
  'a',
  'healthy',
  'food',
  'but',
  'it',
  'is',
  'an',
  'excellent',
  'food',
  'for',
  'teenagers'],
 ['the',
  'plate',
  'has',
  'one',
  'of',
  'my',
  'favorite',
  'foods',
  'on',
  'it',
  'french',
  'fries'],
 ['it', 'was', 'disgusting', 'food', 'not', 'just', 'bad', 'food'],
 ['a', 'plat

In [66]:
from transformers import DistilBertTokenizer, DistilBertModel




C:\Users\Pakistan\anaconda3\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Pakistan\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_transform.weight', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [78]:
labels1=labels.copy()

In [101]:
positive_captions=[]

for i in range(len(labels)):
    if(labels[i]=='1'):
        positive_captions.append(captions2[i])
        

In [102]:
labels[0]

'1'

In [ ]:
import gensim.downloader as api

# Download the pre-trained embeddings
word_vectors = api.load('glove-wiki-gigaword-50')

In [138]:
#pre trained word embeddings ko use kr kei captions ko numerical vector mei kiya , phir inhe concat kiya ot pythoch tensor mei 
#chnage kiya The model is trained using the concatenated caption vectors and the numerical sentiment labels model phir concatenated 
#numerical captions or numerical sentiment labels per hua train adam optimizer use hua optimization kaam kwi liye.


In [140]:
import torch
import torch.nn as nn
import torch.optim as optim
from gensim.models import KeyedVectors
import nltk

class CaptionModel(nn.Module):
#initializes all objects 
    def __init__(self, input_size, hidden_size, output_size):
        super(CaptionModel, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)
        
#take numberical vector of text whih made by pre existing embeddings
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        x = self.softmax(x)
        return x



# Convert captions to numerical vectors using word embeddings
# Load the pre-trained DistilBERT tokenizer and model
# tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
# model = DistilBertModel.from_pretrained('distilbert-base-uncased')

#code loads pre-trained word embeddings using the DistilBertModel and DistilBertTokenizer classes from the transformers package,
#and uses them to convert a set of image captions into numerical vectors. These caption vectors are concatenated and converted 
#to a PyTorch tensor. A label encoder is then fitted to a set of sentiment labels and the labels are converted to numerical 
#values

caption_vectors = []
for caption in captions2:
    # Tokenize the caption and convert it to IDs
    input_ids = torch.tensor([tokenizer.encode(caption, add_special_tokens=True)])
    # Generate the embedding for the input IDs
    with torch.no_grad():
        outputs = model(input_ids)
        embeddings = outputs.last_hidden_state.mean(dim=1)
        caption_vectors.append(embeddings)

# Concatenate the caption vectors and convert them to a tensor
caption_vectors = torch.cat(caption_vectors) 
   
#label encoder is then fitted to a set of sentiment labels and the labels are converted to numerical values.
# Fit the encoder to the label batch
label_encoder.fit(labels1)

# Convert the label batch to numerical values
label_batch = label_encoder.transform(labels1)

        
label_batch1 = torch.tensor(label_batch, dtype=torch.long)    
    
    
input_size = caption_vectors.size()[1] # dimensionality of the word embeddings
hidden_size = 64 # number of hidden units in each hidden layer
output_size = 2 # number of possible sentiment labels
num_epochs = 10 # number of times to go through the dataset during training

model = CaptionModel(input_size, hidden_size, output_size)
loss_fn = nn.CrossEntropyLoss()
#initializes the optimizer used to update the parameters of the neural network during training. In this case, the optimizer
#being used is Adam, which is a popular optimization algorithm used in deep learning.
#The model.parameters() function returns all the parameters (weights and biases) of the model that need to be updated during 
#training. The optimizer uses these parameters to compute and apply the gradients to update the model weights in the direction 
#of minimizing the loss function  optimizer = optim.Adam(model.parameters())

# Train the model
#The model is trained using the concatenated caption vectors and the numerical sentiment labels. The model's parameters are 
#optimized using the Adam optimizer and the cross-entropy loss function
for epoch in range(num_epochs):
    optimizer.zero_grad()
    outputs = model(caption_vectors)
    loss = loss_fn(outputs, label_batch1)
    loss.backward()
    optimizer.step()

# Generate positive captions using the model
#the model is used to classify the sentiment of a set of positive captions. The captions are converted to vectors using pre-trained word 
#embeddings, and the vectors are passed through the trained model to obtain the probabilities of positive and negative 
#sentiment labels. The probability of a positive label is extracted from the model output and stored in positive_prob
with torch.no_grad():
    for caption in positive_captions:
        #print("neha")
        vector = []
        #splits the caption string into a list of words using whitespace as the delimiter and assigns the result to the 
        #variable words
        words = caption.split()
        #creates a list called vectors by iterating through each word in words. For each word, it checks if it exists in 
        #the key_to_index attribute of word_vectors. If it does, it appends the corresponding vector to vectors. This is a way
        #to convert the text into numerical vectors using pre-trained word embeddings
        vectors = [word_vectors[word] for word in words if word in word_vectors.key_to_index]
        if vectors:
            #print("neha1")
            #If vectors is not empty, it calculates the mean of the vectors and appends it to the vector list
            vector_mean = sum(vectors) / len(vectors)
            vector.append(vector_mean)
        #converts the vector list to a PyTorch tensor
        vector = torch.Tensor(vector)
        output = model(vector)
        #This extracts the output probabilities from the model, which represent the probability of each sentiment class.
        sentiment_probs = output[0]
        #extracts the probability of the positive sentiment class (index 1) and converts it to a Python float. This represents 
        #the probability that the input caption has a positive sentiment.
        positive_prob = sentiment_probs[1].item()

        
# Generate positive captions using the model
with torch.no_grad():
    num_correct = 0
    num_total = 0
    for caption, label in zip(positive_captions, labels1):
        vector = []
        words = caption.split()
        vectors = [word_vectors[word] for word in words if word in word_vectors.key_to_index]
        if vectors:
            vector_mean = sum(vectors) / len(vectors)
            vector.append(vector_mean)
        vector = torch.Tensor(vector)
        output = model(vector)
        sentiment_probs = output[0]
        positive_prob = sentiment_probs[1].item()
        if positive_prob > 0.5:
            num_correct += 1
        num_total += 1
    accuracy = num_correct / num_total
    print("Accuracy: {:.2f}%".format(accuracy * 100))


neha
neha1
Accuracy: 20.00%


In [132]:
caption_vectors

tensor([[ 0.0573, -0.1531, -0.1188,  ..., -0.0097,  0.1334, -0.1902],
        [ 0.0151,  0.0967, -0.0227,  ..., -0.1298,  0.0968, -0.0235],
        [-0.0045,  0.1852, -0.0592,  ...,  0.1166,  0.0889, -0.0729],
        ...,
        [ 0.0253, -0.1259, -0.1781,  ..., -0.2764, -0.1065,  0.0970],
        [ 0.2234,  0.0959, -0.2907,  ..., -0.0484,  0.1503,  0.0788],
        [ 0.0183, -0.1115, -0.3642,  ..., -0.0584,  0.2069,  0.0217]])

In [131]:
caption_vectors=caption_vectors1

In [76]:
caption_vectors1=caption_vectors

In [ ]:
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self, image_features_dim, text_features_dim, hidden_dim,num_classes):
        super(MyModel, self).__init__()
        
        self.image_features_dim = image_features_dim
        self.text_features_dim = text_features_dim
        self.hidden_dim = hidden_dim
        
        # Define layers
        self.text_hidden_layer = nn.Linear(text_features_dim, hidden_dim)
        self.image_hidden_layer = nn.Linear(image_features_dim, hidden_dim)
        self.hidden_layer1 = nn.Linear(hidden_dim, hidden_dim)
        self.hidden_layer2 = nn.Linear(hidden_dim, hidden_dim)
        self.hidden_layer3 = nn.Linear(hidden_dim, hidden_dim)
        self.hidden_layer4 = nn.Linear(hidden_dim, hidden_dim)
        self.output_layer = nn.Linear(hidden_dim, num_classes) # num_classes is the number of output classes
        
    def forward(self, text_features, image_features,text_features_dim,image_features_dim):
        print("neha2")
        image_hidden = self.image_hidden_layer(image_features)
        image_hidden = nn.functional.relu(image_hidden)
        
        
        print("neha1")
        print(text_features.shape[0])
        text_hidden = self.text_hidden_layer(text_features)
        text_hidden = nn.functional.relu(text_hidden)
        
        print("neha3")
        print(text_hidden.size())
        print(image_hidden.size())
            
        text_hidden = text_hidden.transpose(0, 1)
        image_hidden = image_hidden.transpose(0, 1)
    
        # Concatenate text and image hidden layers
        concat_hidden = torch.cat([text_hidden, image_hidden],dim=1)
        
        print("neha4")
         
 
        # Pass through additional hidden layers
        concat_hidden = concat_hidden.transpose(0, 1)
        #concat_hidden=torch.cat([concat_hidden, concat_hidden], dim=1)
        
        print(concat_hidden.size())
        #hidden1_transpose = self.hidden_layer1.weight.t()
    
        hidden1 = self.hidden_layer1(concat_hidden)  # Transpose again to get the original shape
        hidden1 = nn.functional.relu(hidden1)

        
 
        print("neha5")
        hidden2 = self.hidden_layer2(hidden1)
        hidden2 = nn.functional.relu(hidden2)
        print("neha6")
        hidden3 = self.hidden_layer3(hidden2)
        hidden3 = nn.functional.relu(hidden3)
        print("neha7")
        hidden4 = self.hidden_layer4(hidden3)
        hidden4 = nn.functional.relu(hidden4)
        print("neha8")
        # Pass through output layer
        output = self.output_layer(hidden4)
        
        return output

    
num_samples = len(imagefiles)
image_feature_dim = imagefiles[0].shape[1] # Assumes all image features have same dimensions
print("image_feature_dim",image_feature_dim)
text_feature_dim = padded_data.shape[1]
print("text_feature_dim",text_feature_dim)
 
image_features_tensor =imagefiles           #torch.stack(imagefiles, dim=0) 
image_features_tensor = image_features_tensor.view(-1, 25088)


text_features_array = padded_data[0, :, :]
text_features_array /= np.linalg.norm(text_features_array, axis=-1, keepdims=True)

text_features_tensor = torch.Tensor(text_features_array)
text_features_dim = text_features_array.shape[-1]  # num_features

    
model = MyModel(image_features_dim=image_feature_dim, text_features_dim=text_features_dim, hidden_dim=50, num_classes=10)

# Call the forward method of the model to get the output
output = model.forward(text_features_tensor, image_features_tensor, text_features_dim, image_features_dim=image_features_tensor.shape[1])

 
